services:
  - type: web
    name: skylink-auth-api
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: JWT_SECRET
        generateValue: true
